global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'volharvester'
    static_configs:
      - targets: ['app:9090']
        labels:
          service: 'volatility-harvester'
